#ifndef STATUS_CODES_H
#define STATUS_CODES_H

enum status_code {
    SUCCESS,
    UNKNOWN_ERROR,
    LABEL_NOT_FOUND,
    DATA_TYPE_NOT_FOUND,
    FAILED_OPENING_FILE,
    LABEL_ALREADY_EXISTS,
    MACRO_ALREADY_EXISTS,
    ILLEGAL_OPERAND,
    ILLEGAL_LABEL,
    UNKNOWN_LINE_TYPE,
    FILE_FAILED
};

#endif
